# Generated by Django 3.2.4 on 2022-12-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minha_app', '0002_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='responsible',
            field=models.CharField(max_length=300),
        ),
    ]
